version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=johndoe
      - POSTGRES_PASSWORD=randompassword
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgres/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - postgres
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: unless-stopped
  patient-api:
    container_name: patient-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT = ${PORT}
    volumes:
      - ./:/usr/api/dev
      - ignore:/usr/api/node_modules/
    ports:
      - 3001:${PORT}
    env_file:
      - .env
    depends_on:
      - postgres
    links:
      - postgres
volumes:
  ignore:
  pgadmin-data:
  db:
    driver: local
  