services:
  myapp:
    container_name: reservation-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT = ${PORT}
    volumes:
      - ./:/usr/local/apps/myapp/dev
      - ignore:/usr/local/apps/myapp/dev/node_modules/
    ports:
      - 3001:${PORT}
    env_file:
      - .env
volumes:
  ignore: